/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutorial;

/**
 * @author Abel Herrero Gómez           (abeherr)
 * @author Héctor Hilanderas Pizarro    (hechila)
 */
public class FrameTutorial extends javax.swing.JFrame {

    /**
     * Creates new form FrameTutorial
     */
    public FrameTutorial() {
        initComponents();
        this.setLocationRelativeTo(null);   // Para centrar en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCalculadora = new javax.swing.JPanel();
        lValor1 = new javax.swing.JLabel();
        lValor2 = new javax.swing.JLabel();
        lResultado = new javax.swing.JLabel();
        tfValor1 = new javax.swing.JTextField();
        tfValor2 = new javax.swing.JTextField();
        tfResultado = new javax.swing.JTextField();
        btnDividir = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));

        jpCalculadora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Calculadora   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rubik", 0, 18), new java.awt.Color(0, 102, 255))); // NOI18N
        jpCalculadora.setForeground(new java.awt.Color(255, 255, 255));
        jpCalculadora.setToolTipText("");

        lValor1.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        lValor1.setLabelFor(lValor1);
        lValor1.setText("Valor 1:");
        lValor1.setToolTipText("");

        lValor2.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        lValor2.setLabelFor(tfValor2);
        lValor2.setText("Valor 2:");

        lResultado.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        lResultado.setLabelFor(tfResultado);
        lResultado.setText("Resultado:");

        tfValor1.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N

        tfValor2.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N

        tfResultado.setEditable(false);
        tfResultado.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N

        btnDividir.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        btnDividir.setText("DIVIDIR");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnSumar.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        btnSumar.setText("SUMAR");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnRestar.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        btnRestar.setText("RESTAR");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        btnMultiplicar.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        btnMultiplicar.setText("MULTIPLICAR");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCalculadoraLayout = new javax.swing.GroupLayout(jpCalculadora);
        jpCalculadora.setLayout(jpCalculadoraLayout);
        jpCalculadoraLayout.setHorizontalGroup(
            jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCalculadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCalculadoraLayout.createSequentialGroup()
                        .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCalculadoraLayout.createSequentialGroup()
                        .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCalculadoraLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lResultado)
                            .addComponent(lValor2)
                            .addComponent(lValor1))
                        .addGap(18, 18, 18)
                        .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfValor1)
                            .addComponent(tfValor2)
                            .addComponent(tfResultado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCalculadoraLayout.setVerticalGroup(
            jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCalculadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lValor1))
                .addGap(18, 18, 18)
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lValor2))
                .addGap(18, 18, 18)
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lResultado)
                    .addComponent(tfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpiar.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(300, 55));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jpCalculadora.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        if(comprobarValores()){
            float f1 = Float.parseFloat(tfValor1.getText());
            float f2 = Float.parseFloat(tfValor2.getText());
            tfResultado.setText(Float.toString(f1 + f2));
        }  
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        if(comprobarValores()){
            float f1 = Float.parseFloat(tfValor1.getText());
            float f2 = Float.parseFloat(tfValor2.getText());
            if(f1 == 0.0 && f2 == 0.0){
                tfResultado.setText("Indeterminación");
            }else{
                tfResultado.setText(Float.toString(f1 / f2));
            }
        } 
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        if(comprobarValores()){
            float f1 = Float.parseFloat(tfValor1.getText());
            float f2 = Float.parseFloat(tfValor2.getText());
            tfResultado.setText(Float.toString(f1 * f2));
        } 
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        tfValor1.setText("");
        tfValor2.setText("");
        tfResultado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        if(comprobarValores()){
            float f1 = Float.parseFloat(tfValor1.getText());
            float f2 = Float.parseFloat(tfValor2.getText());
            tfResultado.setText(Float.toString(f1 - f2));
        } 
    }//GEN-LAST:event_btnRestarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTutorial().setVisible(true);
            }
        });
    }
    
    /**
     * Comprueba si los valores de entrada son válidos o no.
     * 
     * @return true si son válidos, false si no
     */
    public boolean comprobarValores(){
        boolean res = true;
        
        String v1 = tfValor1.getText();
        String v2 = tfValor2.getText();
        
        try{
            Float.parseFloat(v1);
        }catch(Exception e){
            tfValor1.setText("");
            res = false;
        }
        
        try{
            Float.parseFloat(v2);
        }catch(Exception e){
            tfValor2.setText("");
            res = false;
        }
        
        
        return res;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JPanel jpCalculadora;
    private javax.swing.JLabel lResultado;
    private javax.swing.JLabel lValor1;
    private javax.swing.JLabel lValor2;
    private javax.swing.JTextField tfResultado;
    private javax.swing.JTextField tfValor1;
    private javax.swing.JTextField tfValor2;
    // End of variables declaration//GEN-END:variables
}
